# Generated by Django 4.2.7 on 2025-10-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'managed': False},
        ),
    ]
