# Generated by Django 4.2.7 on 2025-10-04 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0002_add_voice_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, help_text="e.g., 'The Brave', 'Shadow Walker'", max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description used for AI backstory generation', null=True)),
                ('backstory', models.TextField(blank=True, null=True)),
                ('personality_traits', models.JSONField(default=list, help_text='List of personality traits: brave, cunning, wise, etc.')),
                ('blooms_level', models.CharField(choices=[('remembering', 'Novice - Recall facts and basic concepts'), ('understanding', 'Apprentice - Explain ideas or concepts'), ('applying', 'Journeyman - Use information in new situations'), ('analyzing', 'Expert - Draw connections among ideas'), ('evaluating', 'Master - Justify a stand or decision'), ('creating', 'Grandmaster - Produce new or original work')], default='remembering', help_text="Character's Personal Evolution Arc level", max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.CharField(blank=True, help_text="e.g., '6 feet', '1.8 meters'", max_length=50, null=True)),
                ('appearance', models.TextField(blank=True, help_text='Physical description', null=True)),
                ('level', models.IntegerField(default=1)),
                ('experience_points', models.IntegerField(default=0)),
                ('attributes', models.JSONField(default=dict, help_text='Character attributes: strength, dexterity, intelligence, wisdom, etc.')),
                ('skills', models.JSONField(default=list, help_text='List of character skills')),
                ('inventory', models.JSONField(default=list, help_text="Character's inventory items")),
                ('voice_profile', models.JSONField(default=dict, help_text='Voice characteristics, accent, speaking patterns, and language proficiencies')),
                ('images', models.JSONField(default=list, help_text='List of image URLs for this character (max 4)')),
                ('primary_image_index', models.IntegerField(default=0, help_text='Index of the primary image in the images list')),
                ('is_active', models.BooleanField(default=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'characters',
                'managed': False,
            },
        ),
    ]
